### ISSUE TITLE
faster reading of many files

### ISSUE THREAD

**Issue by r2evans** [PascalKieslich/readbulk#1]
(Not a user, but the issue came up on SO: https://stackoverflow.com/q/51161385/3358272)

A user was complaining about read-times getting longer as the reading progressed. On seeing how he was using this function and reading the source, I see that you are iterating over each file and appending it to `all_data`. The `rbind` op (whether using `base` or `plyr`) is expensive in that it makes a full copy every time. With many files, this unnecessarily copies old data many times.

I suggest an alternative that will give a speed-up commensurate with the number of files: capture `read.csv` (or whatever) for each file, then `rbind` (or `rbind.fill`) at the end, such as given here: https://stackoverflow.com/a/23555961/3358272. Something like:

```r
lst <- lapply(files, function(fn) read.csv(fun, ...))
results <- do.call(plyr::rbind.fill, lst)
```

I know you're doing several other things in `read_bulk` under-the-hood (e.g., with `subdirectories`), so the solution would likely require first gathering all filenames (convert all `files` and `subdirectories` into a single vector of full-path-name filenames).

Just a thought, thanks for hearing me out :-)

**Comment by PascalKieslich** [comment]
Thanks for bringing this up! So far, we haven't really optimized `read_bulk` for speed, as our use cases (reading experiment data files - which are usually relatively small each - from a few hundred participants in the lab) worked fine. Thanks for your suggestions as well - I am currently teaching a workshop at a summer school but will look at them by the end of the week and will try to optimize `read_bulk` accordingly (might also switch to `bind_rows` from the `dplyr` package while I am at it).

**Comment by r2evans** [comment]
In that case, congratulations! Someone is using your package in a way not initially foreseen!

**Comment by r2evans** [comment]
A thought: the speed improvement of `dplyr::bind_rows` is good over `plyr::rbind.fill` and even better against `do.call(rbind.data.frame, ...)`. (In a small test, I found `dplyr::bind_rows` to be near 2 OOM faster than base.) However, *requiring* it might be a little heavy-handed, especially as `tidyverse` dependencies grow.

If you instead use `Suggests: dplyr` (in `NAMESPACE`, and some note in the readme), and use some logic like:

```r
if (requireNamespace("dplyr",quietly=TRUE)) {
  results <- dplyr::bind_rows(lst)
} else {
  results <- do.call(rbind.data.frame, lst)
}
```

you might be able to reduce your dependency graph and appeal to users who have not yet "seen the light of the `tidyverse`" ;-)

**Comment by PascalKieslich** [comment]
Thanks again for your suggestion! I have updated the `read_bulk` function accordingly. I also decided to keep relying on `plyr::rbind.fill` for the time being.
